<template>
  <div
    class="distortion"
    @mouseover="mouseHover"
    @mouseleave="mouseLeaver"
  />
  <div
    ref="distortionTitle"
    class="distortion-title"
  >
    <h1>image generated by ai vs original</h1>
  </div>
</template>

<script>
  import HoverEffect from 'hover-effect'
  import anime from "animejs"
  export default {
    name: "DistortionImage",
    mounted() {
      this.animeImage()
      this.prepareHoverAnimation()
    },
    methods: {
      animeImage() {
        new HoverEffect({
          parent: document.querySelector('.distortion'),
          intensity: 0.3,
          image1: 'me_ai.png',
          image2: 'me_back.png',
          displacementImage: 'distort.png'
        })
      },
      prepareHoverAnimation() {
        const { distortionTitle } = this.$refs
        distortionTitle.innerHTML = distortionTitle.textContent
          .replace(/\S/g, "<span style='opacity: 0' class='letter'>$&</span>")
      },
      mouseHover() {
        anime.timeline({loop: false})
          .add({
            targets: '.distortion-title .letter',
            translateX: [80,0],
            translateZ: 0,
            opacity: [0,1],
            easing: "easeOutExpo",
            duration: 1400,
            delay: (el, i) => 100 + 40 * i
          })
      },
      mouseLeaver() {
        anime.timeline({loop: false})
          .add({
            targets: '.distortion-title .letter',
            translateX: [0,-80],
            opacity: [1,0],
            easing: "easeInExpo",
            duration: 800,
            delay: (el, i) => 40 * i
          })
      }
    }
  }
</script>

<style>
  .distortion {
      width: 38vw;
      height: 80vh;
      align-self: flex-end;
  }

  .distortion-title {
      margin-top: 1em;
  }

  .letter {
      font-style: italic;
      text-transform: uppercase;
  }
</style>
